[workspace]
resolver = "3"
members = ["stark-backend", "modules/wallet-monitor-types", "modules/wallet-monitor-service", "modules/discord-tipping-types", "modules/discord-tipping-service", "modules/social-monitor-types", "modules/social-monitor-service"]
